# Form implementation generated from reading ui file 'designer\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from control.DeviceInputTabWidget import DeviceInputTabWidget
from control.ActionTestWidget import ActionTestWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainLayout = QtWidgets.QVBoxLayout()
        self.MainLayout.setObjectName("MainLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")

        self.DeviceInputTab = QtWidgets.QWidget()
        self.DeviceInputTab.setObjectName("DeviceInputTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.DeviceInputTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.DeviceInputTabLayout = QtWidgets.QVBoxLayout()
        self.DeviceInputTabLayout.setObjectName("DeviceInputTabLayout")
        self.__init_DeviceInputTabWidget()
        self.verticalLayout_3.addLayout(self.DeviceInputTabLayout)
        self.tabWidget.addTab(self.DeviceInputTab, "")

        self.ActionTestTab = QtWidgets.QWidget()
        self.ActionTestTab.setObjectName("ActionTestTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.ActionTestTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ActionTestTabLayout = QtWidgets.QVBoxLayout()
        self.ActionTestTabLayout.setObjectName("ActionTestTabLayout")
        self.__init_ActionTestWidget()
        self.verticalLayout_5.addLayout(self.ActionTestTabLayout)
        self.tabWidget.addTab(self.ActionTestTab, "")
        self.MainLayout.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.MainLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu.addSeparator()
        self.menu.addAction(self.actionAbout)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BDO Suffering 辅助开发工具"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DeviceInputTab), _translate("MainWindow", "键鼠输入"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ActionTestTab), _translate("MainWindow", "动作测试"))
        self.tabWidget.setCurrentIndex(0)
        self.menu.setTitle(_translate("MainWindow", "其他"))
        self.actionAbout.setText(_translate("MainWindow", "关于"))

    def __init_DeviceInputTabWidget(self):
        self.DeviceInputTabWidget = DeviceInputTabWidget(self.DeviceInputTab)
        self.DeviceInputTabLayout.addWidget(self.DeviceInputTabWidget)

    def __init_ActionTestWidget(self):
        self.ActionTestWidget = ActionTestWidget(self.ActionTestTab)
        self.ActionTestTabLayout.addWidget(self.ActionTestWidget)
