# Form implementation generated from reading ui file 'designer/MenuOtherAboutDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(336, 190)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.LicenseTitle = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.LicenseTitle.setFont(font)
        self.LicenseTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LicenseTitle.setObjectName("LicenseTitle")
        self.verticalLayout.addWidget(self.LicenseTitle)
        self.License = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        self.License.setFont(font)
        self.License.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.License.setOpenExternalLinks(False)
        self.License.setObjectName("License")
        self.verticalLayout.addWidget(self.License)
        self.projectTitle = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.projectTitle.setFont(font)
        self.projectTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.projectTitle.setObjectName("projectTitle")
        self.verticalLayout.addWidget(self.projectTitle)
        self.github = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(True)
        self.github.setFont(font)
        self.github.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.github.setObjectName("github")
        self.verticalLayout.addWidget(self.github)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "关于"))
        self.LicenseTitle.setText(_translate("Dialog", "License"))
        self.License.setText(_translate("Dialog", "<html><head/><body><p><a href=\"https://www.gnu.org/licenses/gpl-3.0.en.html\"><span style=\" color:#0000ff;\">GPL-3.0</span></a></p><p><a href=\"https://www.gnu.org/licenses/gpl-3.0.en.html\"><span style=\" font-style:normal; color:#710000;\">禁止商用</span></a></p></body></html>"))
        self.projectTitle.setText(_translate("Dialog", "About this project, more info you can fellow: "))
        self.github.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#0000ff;\">SuFIND@github</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">if you have any good idea or bug report, you can take a issue in github.</p></body></html>"))
